spring.application.name=scm2.0

server.port=8081
#mySql database configuration
#datasource url
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=Saurabh@123

#jpa configuration
spring.jpa.show-sql=true
#for creating schemas and table
spring.jpa.hibernate.ddl-auto=update


#Security configuration

# spring.security.user.name=Saurabh
# spring.security.user.password=Saurabh@123

#oauth2 client configuration
#google config
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=930159080514-8rmmsu58fk2u4ce39vtr00fenaj0qag0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid, profile, email


#github config

spring.security.oauth2.client.registration.github.client-id=Iv23liC1LdpBasygFqJG
spring.security.oauth2.client.registration.github.client-secret=6d292450d87308e289660d3ac02eed54f1a89167
spring.security.oauth2.client.registration.github.scope=profile, email


#cloudinary Configuration
cloudinary.cloud.name=dktepoc9p
cloudinary.api.key=599111544859999
cloudinary.api.secret=c26Ab3KNRhP-yhvmlYu68pgGq8Q


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB